require("dotenv").config();

const express = require("express");
const cookieSession = require("cookie-session");
const bcrypt = require("bcryptjs");
const PDFDocument = require("pdfkit");
const path = require("path");
const db = require("./db");

const app = express();
const PORT = process.env.PORT || 3000;
const SESSION_SECRET = process.env.SESSION_SECRET || "dev-secret-change-me";

app.use(express.json({ limit: "2mb" }));
app.use(express.urlencoded({ extended: true }));

app.use(cookieSession({
  name: "beaumont_session",
  keys: [SESSION_SECRET],
  httpOnly: true,
  sameSite: "lax",
  secure: process.env.NODE_ENV === "production",
  maxAge: 1000 * 60 * 60 * 12
}));

app.use(express.static(path.join(__dirname, "..", "public")));

function auth(req, res, next) {
  if (!req.session.user) {
    return res.status(401).json({ error: "Oturum gerekli" });
  }
  next();
}

function isoNow() {
  return new Date().toISOString();
}

function num(v) {
  const n = Number(v);
  return Number.isFinite(n) ? n : 0;
}

async function initDatabase() {
  await db.query(`
    CREATE TABLE IF NOT EXISTS users (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      email TEXT NOT NULL UNIQUE,
      password_hash TEXT NOT NULL,
      name TEXT NOT NULL,
      created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS stocks (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      qty INTEGER NOT NULL DEFAULT 0,
      humidor TEXT,
      sale_price REAL NOT NULL DEFAULT 0,
      cost_price REAL NOT NULL DEFAULT 0,
      pack_qty INTEGER NOT NULL DEFAULT 1,
      created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS customers (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      phone TEXT,
      notes TEXT,
      created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS customer_addresses (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
      title TEXT NOT NULL,
      address TEXT NOT NULL
    );

    CREATE TABLE IF NOT EXISTS orders (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      customer_id INTEGER REFERENCES customers(id) ON DELETE SET NULL,
      buyer_name TEXT NOT NULL,
      phone TEXT,
      address TEXT,
      manual_note TEXT,
      order_date TEXT NOT NULL,
      revenue REAL NOT NULL DEFAULT 0,
      profit REAL NOT NULL DEFAULT 0,
      created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS order_items (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
      stock_id INTEGER REFERENCES stocks(id) ON DELETE SET NULL,
      product_name TEXT NOT NULL,
      qty INTEGER NOT NULL,
      sale_price REAL NOT NULL,
      cost_price REAL NOT NULL
    );

    CREATE TABLE IF NOT EXISTS transactions (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      order_id INTEGER REFERENCES orders(id) ON DELETE CASCADE,
      type TEXT NOT NULL,
      category TEXT NOT NULL,
      description TEXT,
      amount REAL NOT NULL,
      tx_date TEXT NOT NULL
    );

    CREATE TABLE IF NOT EXISTS events (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      title TEXT NOT NULL,
      menu TEXT,
      venue TEXT,
      event_date TEXT NOT NULL,
      event_time TEXT,
      fee REAL NOT NULL DEFAULT 0,
      members TEXT,
      income REAL NOT NULL DEFAULT 0,
      expense REAL NOT NULL DEFAULT 0,
      profit REAL NOT NULL DEFAULT 0
    );

    CREATE TABLE IF NOT EXISTS notes (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      title TEXT NOT NULL,
      body TEXT,
      updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS debts (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      person TEXT NOT NULL,
      type TEXT NOT NULL,
      description TEXT,
      amount REAL NOT NULL DEFAULT 0,
      status TEXT NOT NULL DEFAULT 'Açık'
    );
  `);

  const adminEmail = process.env.ADMIN_EMAIL || "admin@beaumont.local";
  const adminPassword = process.env.ADMIN_PASSWORD || "ChangeMe123!";

  const existing = await db.query(
    "SELECT id FROM users WHERE email=$1",
    [adminEmail]
  );

  if (existing.rows.length === 0) {
    await db.query(
      "INSERT INTO users(email,password_hash,name) VALUES($1,$2,$3)",
      [
        adminEmail,
        bcrypt.hashSync(adminPassword, 12),
        "Beaumont Admin"
      ]
    );
  }

  console.log("PostgreSQL hazır.");
}

async function transaction(callback) {
  const client = await db.connect();

  try {
    await client.query("BEGIN");

    const result = await callback({
      query: (text, params = []) => client.query(text, params)
    });

    await client.query("COMMIT");
    return result;
  } catch (error) {
    await client.query("ROLLBACK");
    throw error;
  } finally {
    client.release();
  }
}

/* ---------------- SESSION ---------------- */

app.get("/api/session", (req, res) => {
  res.json({ user: req.session.user || null });
});

app.post("/api/login", async (req, res) => {
  try {
    const { email, password } = req.body;

    const result = await db.query(
      "SELECT * FROM users WHERE email=$1",
      [email]
    );

    const u = result.rows[0];

    if (!u || !bcrypt.compareSync(password || "", u.password_hash)) {
      return res.status(401).json({
        error: "E-posta veya şifre hatalı"
      });
    }

    req.session.user = {
      id: u.id,
      email: u.email,
      name: u.name
    };

    res.json({
      ok: true,
      user: req.session.user
    });
  } catch (e) {
    res.status(500).json({ error: e.message });
  }
});

app.post("/api/logout", (req, res) => {
  req.session = null;
  res.json({ ok: true });
});

/* ---------------- RATES ---------------- */

app.get("/api/rates", async (req, res) => {
  try {
    const r = await fetch(
      "https://www.tcmb.gov.tr/kurlar/today.xml"
    );

    if (!r.ok) {
      throw new Error("TCMB kur servisi cevap vermedi");
    }

    const xml = await r.text();

    const getRate = (code) => {
      const match = xml.match(
        new RegExp(
          `<Currency[^>]*Kod="${code}"[\\s\\S]*?<ForexBuying>(.*?)</ForexBuying>`
        )
      );

      return match ? Number(match[1].replace(",", ".")) : null;
    };

    const eurTRY = getRate("EUR");
    const usdTRY = getRate("USD");
    const gbpTRY = getRate("GBP");
    const chfTRY = getRate("CHF");

    if (!eurTRY || !usdTRY || !gbpTRY || !chfTRY) {
      throw new Error("TCMB kurları okunamadı");
    }

    res.json({
      base: "EUR",
      rates: {
        EUR: 1,
        USD: eurTRY / usdTRY,
        GBP: eurTRY / gbpTRY,
        CHF: eurTRY / chfTRY,
        TRY: eurTRY
      }
    });
  } catch (e) {
    console.error("Döviz kuru hatası:", e.message);

    res.status(503).json({
      error: "Döviz kurları şu anda alınamadı"
    });
  }
});
/* ---------------- DASHBOARD ---------------- */

app.get("/api/dashboard", auth, async (req, res) => {
  try {
    const today = new Date().toISOString().slice(0, 10);
    const month = today.slice(0, 7);

    const todayOrders = await db.query(
      "SELECT COUNT(*)::int AS c FROM orders WHERE LEFT(order_date,10)=$1",
      [today]
    );

    const mo = await db.query(
      `SELECT
        COUNT(*)::int AS c,
        COALESCE(SUM(revenue),0) AS revenue,
        COALESCE(SUM(profit),0) AS profit
       FROM orders
       WHERE LEFT(order_date,7)=$1`,
      [month]
    );

    const events = await db.query(
      "SELECT * FROM events WHERE event_date=$1 ORDER BY event_time",
      [today]
    );

    const lowStock = await db.query(
      "SELECT * FROM stocks WHERE qty<=5 ORDER BY qty,name LIMIT 10"
    );

    res.json({
      today,
      todayOrders: todayOrders.rows[0].c,
      monthOrders: mo.rows[0].c,
      monthRevenue: Number(mo.rows[0].revenue),
      monthProfit: Number(mo.rows[0].profit),
      events: events.rows,
      lowStock: lowStock.rows
    });
  } catch (e) {
    res.status(500).json({ error: e.message });
  }
});

/* ---------------- STOCKS ---------------- */

app.get("/api/stocks", auth, async (req, res) => {
  const r = await db.query("SELECT * FROM stocks ORDER BY name");
  res.json(r.rows);
});

app.post("/api/stocks", auth, async (req, res) => {
  try {
    const b = req.body;

    const r = await db.query(
      `INSERT INTO stocks
       (name,qty,humidor,sale_price,cost_price,pack_qty)
       VALUES($1,$2,$3,$4,$5,$6)
       RETURNING id`,
      [
        b.name,
        num(b.qty),
        b.humidor || "",
        num(b.sale_price),
        num(b.cost_price),
        Math.max(1, num(b.pack_qty) || 1)
      ]
    );

    res.json({ id: r.rows[0].id });
  } catch (e) {
    res.status(400).json({ error: e.message });
  }
});

app.put("/api/stocks/:id", auth, async (req, res) => {
  try {
    const b = req.body;

    await db.query(
      `UPDATE stocks
       SET name=$1,qty=$2,humidor=$3,sale_price=$4,cost_price=$5,pack_qty=$6
       WHERE id=$7`,
      [
        b.name,
        num(b.qty),
        b.humidor || "",
        num(b.sale_price),
        num(b.cost_price),
        Math.max(1, num(b.pack_qty) || 1),
        req.params.id
      ]
    );

    res.json({ ok: true });
  } catch (e) {
    res.status(400).json({ error: e.message });
  }
});

app.delete("/api/stocks/:id", auth, async (req, res) => {
  await db.query(
    "DELETE FROM stocks WHERE id=$1",
    [req.params.id]
  );

  res.json({ ok: true });
});

app.post("/api/stocks/:id/adjust", auth, async (req, res) => {
  try {
    const delta = num(req.body.delta);

    const r = await db.query(
      "SELECT * FROM stocks WHERE id=$1",
      [req.params.id]
    );

    const s = r.rows[0];

    if (!s) {
      return res.status(404).json({
        error: "Stok bulunamadı"
      });
    }

    const next = Math.max(0, s.qty + delta);

    await db.query(
      "UPDATE stocks SET qty=$1 WHERE id=$2",
      [next, s.id]
    );

    res.json({ qty: next });
  } catch (e) {
    res.status(400).json({ error: e.message });
  }
});

/* ---------------- CUSTOMERS ---------------- */

app.get("/api/customers", auth, async (req, res) => {
  const cs = await db.query(
    "SELECT * FROM customers ORDER BY name"
  );

  const ad = await db.query(
    "SELECT * FROM customer_addresses"
  );

  const map = new Map();

  ad.rows.forEach(a => {
    if (!map.has(a.customer_id)) {
      map.set(a.customer_id, []);
    }

    map.get(a.customer_id).push(a);
  });

  res.json(
    cs.rows.map(c => ({
      ...c,
      addresses: map.get(c.id) || []
    }))
  );
});

app.post("/api/customers", auth, async (req, res) => {
  try {
    const b = req.body;

    const id = await transaction(async ({ query }) => {
      const r = await query(
        `INSERT INTO customers(name,phone,notes)
         VALUES($1,$2,$3)
         RETURNING id`,
        [
          b.name,
          b.phone || "",
          b.notes || ""
        ]
      );

      const customerId = r.rows[0].id;

      for (const a of (b.addresses || [])) {
        if (a.title || a.address) {
          await query(
            `INSERT INTO customer_addresses
             (customer_id,title,address)
             VALUES($1,$2,$3)`,
            [
              customerId,
              a.title || "Adres",
              a.address || ""
            ]
          );
        }
      }

      return customerId;
    });

    res.json({ id });
  } catch (e) {
    res.status(400).json({ error: e.message });
  }
});

app.put("/api/customers/:id", auth, async (req, res) => {
  try {
    const b = req.body;

    await transaction(async ({ query }) => {
      await query(
        `UPDATE customers
         SET name=$1,phone=$2,notes=$3
         WHERE id=$4`,
        [
          b.name,
          b.phone || "",
          b.notes || "",
          req.params.id
        ]
      );

      await query(
        "DELETE FROM customer_addresses WHERE customer_id=$1",
        [req.params.id]
      );

      for (const a of (b.addresses || [])) {
        if (a.title || a.address) {
          await query(
            `INSERT INTO customer_addresses
             (customer_id,title,address)
             VALUES($1,$2,$3)`,
            [
              req.params.id,
              a.title || "Adres",
              a.address || ""
            ]
          );
        }
      }
    });

    res.json({ ok: true });
  } catch (e) {
    res.status(400).json({ error: e.message });
  }
});

app.delete("/api/customers/:id", auth, async (req, res) => {
  await db.query(
    "DELETE FROM customers WHERE id=$1",
    [req.params.id]
  );

  res.json({ ok: true });
});

/* ---------------- ORDERS ---------------- */

app.get("/api/orders", auth, async (req, res) => {
  const orders = await db.query(
    "SELECT * FROM orders ORDER BY order_date DESC"
  );

  const items = await db.query(
    "SELECT * FROM order_items ORDER BY id"
  );

  const map = new Map();

  items.rows.forEach(i => {
    if (!map.has(i.order_id)) {
      map.set(i.order_id, []);
    }

    map.get(i.order_id).push(i);
  });

  res.json(
    orders.rows.map(o => ({
      ...o,
      items: map.get(o.id) || []
    }))
  );
});

app.post("/api/orders", auth, async (req, res) => {
  try {
    const b = req.body;

    if (
      !b.buyer_name ||
      !Array.isArray(b.items) ||
      !b.items.length
    ) {
      return res.status(400).json({
        error: "Alıcı ve en az bir ürün gerekli"
      });
    }

    const orderId = await transaction(async ({ query }) => {
      let revenue = 0;
      let profit = 0;
      const resolved = [];

      for (const it of b.items) {
        const r = await query(
          "SELECT * FROM stocks WHERE id=$1 FOR UPDATE",
          [it.stock_id]
        );

        const s = r.rows[0];
        const q = Math.floor(num(it.qty));

        if (!s || q < 1) {
          throw new Error("Geçersiz ürün");
        }

        if (s.qty < q) {
          throw new Error(`Yetersiz stok: ${s.name}`);
        }

        revenue += Number(s.sale_price) * q;
        profit +=
          (Number(s.sale_price) - Number(s.cost_price)) * q;

        resolved.push({ s, q });
      }

      const order = await query(
        `INSERT INTO orders
         (customer_id,buyer_name,phone,address,manual_note,
          order_date,revenue,profit)
         VALUES($1,$2,$3,$4,$5,$6,$7,$8)
         RETURNING id`,
        [
          b.customer_id || null,
          b.buyer_name,
          b.phone || "",
          b.address || "",
          b.manual_note || "",
          b.order_date || isoNow(),
          revenue,
          profit
        ]
      );

      const id = order.rows[0].id;

      for (const { s, q } of resolved) {
        await query(
          `INSERT INTO order_items
           (order_id,stock_id,product_name,qty,sale_price,cost_price)
           VALUES($1,$2,$3,$4,$5,$6)`,
          [
            id,
            s.id,
            s.name,
            q,
            s.sale_price,
            s.cost_price
          ]
        );

        await query(
          "UPDATE stocks SET qty=qty-$1 WHERE id=$2",
          [q, s.id]
        );
      }

      await query(
        `INSERT INTO transactions
         (order_id,type,category,description,amount,tx_date)
         VALUES($1,$2,$3,$4,$5,$6)`,
        [
          id,
          "income",
          "Satış",
          `Sipariş — ${b.buyer_name}`,
          revenue,
          b.order_date || isoNow()
        ]
      );

      return id;
    });

    res.json({ id: orderId });
  } catch (e) {
    res.status(400).json({ error: e.message });
  }
});

app.delete("/api/orders/:id", auth, async (req, res) => {
  try {
    await transaction(async ({ query }) => {
      const o = await query(
        "SELECT * FROM orders WHERE id=$1 FOR UPDATE",
        [req.params.id]
      );

      const order = o.rows[0];

      if (!order) {
        throw new Error("Sipariş bulunamadı");
      }

      const items = await query(
        "SELECT * FROM order_items WHERE order_id=$1",
        [order.id]
      );

      for (const i of items.rows) {
        if (i.stock_id) {
          await query(
            "UPDATE stocks SET qty=qty+$1 WHERE id=$2",
            [i.qty, i.stock_id]
          );
        }
      }

      await query(
        "DELETE FROM transactions WHERE order_id=$1",
        [order.id]
      );

      await query(
        "DELETE FROM orders WHERE id=$1",
        [order.id]
      );
    });

    res.json({ ok: true });
  } catch (e) {
    res.status(400).json({ error: e.message });
  }
});

/* ---------------- MONTHLY ---------------- */

app.get("/api/monthly/:month", auth, async (req, res) => {
  const m = req.params.month;

  const summary = await db.query(
    `SELECT
      COUNT(*)::int AS count,
      COALESCE(SUM(revenue),0) AS revenue,
      COALESCE(SUM(profit),0) AS profit
     FROM orders
     WHERE LEFT(order_date,7)=$1`,
    [m]
  );

  const orders = await db.query(
    `SELECT * FROM orders
     WHERE LEFT(order_date,7)=$1
     ORDER BY order_date DESC`,
    [m]
  );

  const tx = await db.query(
    `SELECT * FROM transactions
     WHERE LEFT(tx_date,7)=$1
     ORDER BY tx_date DESC`,
    [m]
  );

  res.json({
    month: m,
    ...summary.rows[0],
    orders: orders.rows,
    transactions: tx.rows
  });
});

/* ---------------- TRANSACTIONS ---------------- */

app.get("/api/transactions", auth, async (req, res) => {
  const r = await db.query(
    "SELECT * FROM transactions ORDER BY tx_date DESC"
  );

  res.json(r.rows);
});

app.post("/api/transactions", auth, async (req, res) => {
  try {
    const b = req.body;

    const r = await db.query(
      `INSERT INTO transactions
       (type,category,description,amount,tx_date)
       VALUES($1,$2,$3,$4,$5)
       RETURNING id`,
      [
        b.type,
        b.category,
        b.description || "",
        num(b.amount),
        b.tx_date || isoNow()
      ]
    );

    res.json({ id: r.rows[0].id });
  } catch (e) {
    res.status(400).json({ error: e.message });
  }
});

app.delete("/api/transactions/:id", auth, async (req, res) => {
  await db.query(
    "DELETE FROM transactions WHERE id=$1 AND order_id IS NULL",
    [req.params.id]
  );

  res.json({ ok: true });
});

/* ---------------- ECONOMY ---------------- */

app.get("/api/economy/:month", auth, async (req, res) => {
  const m = req.params.month;

  const r = await db.query(
    `SELECT * FROM transactions
     WHERE LEFT(tx_date,7)=$1
     ORDER BY tx_date DESC`,
    [m]
  );

  const rows = r.rows;

  const income = rows
    .filter(x => x.type === "income")
    .reduce((s, x) => s + Number(x.amount), 0);

  const expense = rows
    .filter(x => x.type === "expense")
    .reduce((s, x) => s + Number(x.amount), 0);

  res.json({
    month: m,
    income,
    expense,
    net: income - expense,
    rows
  });
});

/* ---------------- EVENTS ---------------- */

app.get("/api/events", auth, async (req, res) => {
  const r = await db.query(
    "SELECT * FROM events ORDER BY event_date,event_time"
  );

  res.json(r.rows);
});

app.post("/api/events", auth, async (req, res) => {
  try {
    const b = req.body;
    const profit = num(b.income) - num(b.expense);

    const r = await db.query(
      `INSERT INTO events
       (title,menu,venue,event_date,event_time,fee,members,
        income,expense,profit)
       VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
       RETURNING id`,
      [
        b.title,
        b.menu || "",
        b.venue || "",
        b.event_date,
        b.event_time || "",
        num(b.fee),
        b.members || "",
        num(b.income),
        num(b.expense),
        profit
      ]
    );

    res.json({ id: r.rows[0].id });
  } catch (e) {
    res.status(400).json({ error: e.message });
  }
});

app.put("/api/events/:id", auth, async (req, res) => {
  try {
    const b = req.body;
    const profit = num(b.income) - num(b.expense);

    await db.query(
      `UPDATE events SET
       title=$1,menu=$2,venue=$3,event_date=$4,event_time=$5,
       fee=$6,members=$7,income=$8,expense=$9,profit=$10
       WHERE id=$11`,
      [
        b.title,
        b.menu || "",
        b.venue || "",
        b.event_date,
        b.event_time || "",
        num(b.fee),
        b.members || "",
        num(b.income),
        num(b.expense),
        profit,
        req.params.id
      ]
    );

    res.json({ ok: true });
  } catch (e) {
    res.status(400).json({ error: e.message });
  }
});

app.delete("/api/events/:id", auth, async (req, res) => {
  await db.query(
    "DELETE FROM events WHERE id=$1",
    [req.params.id]
  );

  res.json({ ok: true });
});

/* ---------------- NOTES ---------------- */

app.get("/api/notes", auth, async (req, res) => {
  const r = await db.query(
    "SELECT * FROM notes ORDER BY updated_at DESC"
  );

  res.json(r.rows);
});

app.post("/api/notes", auth, async (req, res) => {
  const r = await db.query(
    `INSERT INTO notes(title,body)
     VALUES($1,$2)
     RETURNING id`,
    [
      req.body.title,
      req.body.body || ""
    ]
  );

  res.json({ id: r.rows[0].id });
});

app.put("/api/notes/:id", auth, async (req, res) => {
  await db.query(
    `UPDATE notes
     SET title=$1,body=$2,updated_at=CURRENT_TIMESTAMP
     WHERE id=$3`,
    [
      req.body.title,
      req.body.body || "",
      req.params.id
    ]
  );

  res.json({ ok: true });
});

app.delete("/api/notes/:id", auth, async (req, res) => {
  await db.query(
    "DELETE FROM notes WHERE id=$1",
    [req.params.id]
  );

  res.json({ ok: true });
});

/* ---------------- DEBTS ---------------- */

app.get("/api/debts", auth, async (req, res) => {
  const r = await db.query(
    "SELECT * FROM debts ORDER BY id DESC"
  );

  res.json(r.rows);
});

app.post("/api/debts", auth, async (req, res) => {
  const b = req.body;

  const r = await db.query(
    `INSERT INTO debts
     (person,type,description,amount,status)
     VALUES($1,$2,$3,$4,$5)
     RETURNING id`,
    [
      b.person,
      b.type,
      b.description || "",
      num(b.amount),
      b.status || "Açık"
    ]
  );

  res.json({ id: r.rows[0].id });
});

app.put("/api/debts/:id", auth, async (req, res) => {
  const b = req.body;

  await db.query(
    `UPDATE debts SET
     person=$1,type=$2,description=$3,amount=$4,status=$5
     WHERE id=$6`,
    [
      b.person,
      b.type,
      b.description || "",
      num(b.amount),
      b.status || "Açık",
      req.params.id
    ]
  );

  res.json({ ok: true });
});

app.delete("/api/debts/:id", auth, async (req, res) => {
  await db.query(
    "DELETE FROM debts WHERE id=$1",
    [req.params.id]
  );

  res.json({ ok: true });
});

/* ---------------- PDF ---------------- */

app.get("/api/pdf/monthly/:month", auth, async (req, res) => {
  const m = req.params.month;

  const summary = await db.query(
    `SELECT
      COUNT(*)::int AS count,
      COALESCE(SUM(revenue),0) AS revenue,
      COALESCE(SUM(profit),0) AS profit
     FROM orders
     WHERE LEFT(order_date,7)=$1`,
    [m]
  );

  const orders = await db.query(
    `SELECT * FROM orders
     WHERE LEFT(order_date,7)=$1
     ORDER BY order_date DESC`,
    [m]
  );

  const s = summary.rows[0];

  const doc = new PDFDocument({ margin: 45 });

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename="beaumont-${m}-aylik-ozet.pdf"`
  );

  doc.pipe(res);

  doc.fontSize(22).text("BEAUMONT CLUB", {
    align: "center"
  });

  doc.moveDown(0.3);

  doc.fontSize(16).text(`Aylık Özet — ${m}`, {
    align: "center"
  });

  doc.moveDown();

  doc.fontSize(12).text(`Sipariş: ${s.count}`);
  doc.text(`Ciro: €${Number(s.revenue).toFixed(2)}`);
  doc.text(`Kâr: €${Number(s.profit).toFixed(2)}`);

  doc.moveDown();
  doc.fontSize(14).text("Siparişler");
  doc.moveDown(0.5);

  orders.rows.forEach(o => {
    doc.fontSize(10).text(
      `${o.order_date} | ${o.buyer_name} | Ciro €${Number(o.revenue).toFixed(2)} | Kâr €${Number(o.profit).toFixed(2)}`
    );
  });

  doc.end();
});

app.get("/api/pdf/economy/:month", auth, async (req, res) => {
  const m = req.params.month;

  const r = await db.query(
    `SELECT * FROM transactions
     WHERE LEFT(tx_date,7)=$1
     ORDER BY tx_date DESC`,
    [m]
  );

  const rows = r.rows;

  const income = rows
    .filter(x => x.type === "income")
    .reduce((s, x) => s + Number(x.amount), 0);

  const expense = rows
    .filter(x => x.type === "expense")
    .reduce((s, x) => s + Number(x.amount), 0);

  const doc = new PDFDocument({ margin: 45 });

  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    `attachment; filename="beaumont-${m}-ekonomi.pdf"`
  );

  doc.pipe(res);

  doc.fontSize(22).text("BEAUMONT CLUB", {
    align: "center"
  });

  doc.moveDown(0.3);

  doc.fontSize(16).text(`Ekonomik Durum — ${m}`, {
    align: "center"
  });

  doc.moveDown();

  doc.fontSize(12).text(
    `Toplam Gelir: €${income.toFixed(2)}`
  );

  doc.text(
    `Toplam Gider: €${expense.toFixed(2)}`
  );

  doc.text(
    `Net: €${(income - expense).toFixed(2)}`
  );

  doc.moveDown();
  doc.fontSize(14).text("Hareketler");

  rows.forEach(t => {
    doc.fontSize(10).text(
      `${t.tx_date} | ${t.type === "income" ? "Gelir" : "Gider"} | ${t.category} | ${t.description || ""} | €${Number(t.amount).toFixed(2)}`
    );
  });

  doc.end();
});

/* ---------------- FRONTEND ---------------- */

app.use((req, res) => {
  res.sendFile(
    path.join(__dirname, "..", "public", "index.html")
  );
});

/* ---------------- START ---------------- */

initDatabase()
  .then(() => {
    app.listen(PORT, () => {
      console.log(`Beaumont Club running on http://localhost:${PORT}`);
    });
  })
  .catch(err => {
    console.error("DATABASE BAŞLATMA HATASI:", err);
    process.exit(1);
  });
